/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginDto {
  /** User email */
  email: string;
  /** User password */
  password: string;
}
