/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */

/**
 * User role
 */
export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


export const RegisterDtoRole = {
  PATIENT: 'PATIENT',
  THERAPIST: 'THERAPIST',
  ADMIN: 'ADMIN',
} as const;
