/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */
import type { RegisterDtoRole } from './registerDtoRole';

export interface RegisterDto {
  /** User email */
  email: string;
  /** User password (min 6 chars) */
  password: string;
  /** User role */
  role?: RegisterDtoRole;
}
