/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseDtoAvatar } from './userResponseDtoAvatar';
import type { UserResponseDtoFirstName } from './userResponseDtoFirstName';
import type { UserResponseDtoLastName } from './userResponseDtoLastName';
import type { UserResponseDtoPhone } from './userResponseDtoPhone';
import type { UserResponseDtoRole } from './userResponseDtoRole';

export interface UserResponseDto {
  id: string;
  email: string;
  role: UserResponseDtoRole;
  firstName?: UserResponseDtoFirstName;
  lastName?: UserResponseDtoLastName;
  phone?: UserResponseDtoPhone;
  avatar?: UserResponseDtoAvatar;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}
