/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponseDto,
  ErrorResponseDto,
  LoginDto,
  RegisterDto
} from '../model';

import { apiFetch } from '../../utils/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type authControllerLoginResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authControllerLoginResponse401 = {
  data: ErrorResponseDto
  status: 401
}

export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
export type authControllerLoginResponseError = (authControllerLoginResponse401) & {
  headers: Headers;
};

export type authControllerLoginResponse = (authControllerLoginResponseSuccess | authControllerLoginResponseError)

export const getAuthControllerLoginUrl = () => {




  return `/auth/login`
}

/**
 * Authenticate user with email and password
 * @summary User login
 */
export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {

  return apiFetch<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginDto)
  }
);}





export const getAuthControllerLoginQueryKey = (loginDto?: LoginDto,) => {
    return [
    'POST', `/auth/login`, loginDto
    ] as const;
    }


export const getAuthControllerLoginQueryOptions = <TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorResponseDto>(loginDto: LoginDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerLoginQueryKey(loginDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerLogin>>> = ({ signal }) => authControllerLogin(loginDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthControllerLoginQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
export type AuthControllerLoginQueryError = ErrorResponseDto


/**
 * @summary User login
 */

export function useAuthControllerLogin<TData = Awaited<ReturnType<typeof authControllerLogin>>, TError = ErrorResponseDto>(
 loginDto: LoginDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthControllerLoginQueryOptions(loginDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






export type authControllerRegisterResponse201 = {
  data: AuthResponseDto
  status: 201
}

export type authControllerRegisterResponse400 = {
  data: ErrorResponseDto
  status: 400
}

export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
export type authControllerRegisterResponseError = (authControllerRegisterResponse400) & {
  headers: Headers;
};

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess | authControllerRegisterResponseError)

export const getAuthControllerRegisterUrl = () => {




  return `/auth/register`
}

/**
 * Create a new user account
 * @summary User registration
 */
export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {

  return apiFetch<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registerDto)
  }
);}





export const getAuthControllerRegisterQueryKey = (registerDto?: RegisterDto,) => {
    return [
    'POST', `/auth/register`, registerDto
    ] as const;
    }


export const getAuthControllerRegisterQueryOptions = <TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorResponseDto>(registerDto: RegisterDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthControllerRegisterQueryKey(registerDto);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerRegister>>> = ({ signal }) => authControllerRegister(registerDto, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData> & { queryKey: QueryKey }
}

export type AuthControllerRegisterQueryResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
export type AuthControllerRegisterQueryError = ErrorResponseDto


/**
 * @summary User registration
 */

export function useAuthControllerRegister<TData = Awaited<ReturnType<typeof authControllerRegister>>, TError = ErrorResponseDto>(
 registerDto: RegisterDto, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError, TData>, request?: SecondParameter<typeof apiFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuthControllerRegisterQueryOptions(registerDto,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return withQueryKey(query, queryOptions.queryKey);
}






