/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { apiFetch } from '../../utils/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type appControllerGetHelloResponse200 = {
  data: void
  status: 200
}

export type appControllerGetHelloResponseSuccess = (appControllerGetHelloResponse200) & {
  headers: Headers;
};
;

export type appControllerGetHelloResponse = (appControllerGetHelloResponseSuccess)

export const getAppControllerGetHelloUrl = () => {




  return `/`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<appControllerGetHelloResponse> => {

  return apiFetch<appControllerGetHelloResponse>(getAppControllerGetHelloUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAppControllerGetHelloMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError,void, TContext> => {

const mutationKey = ['appControllerGetHello'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appControllerGetHello>>, void> = () => {


          return  appControllerGetHello(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AppControllerGetHelloMutationResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>

    export type AppControllerGetHelloMutationError = unknown

    export const useAppControllerGetHello = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof appControllerGetHello>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAppControllerGetHelloMutationOptions(options));
    }
