/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  UserResponseDto
} from '../model';

import { apiFetch } from '../../utils/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type usersControllerFindAllResponse200 = {
  data: UserResponseDto[]
  status: 200
}

export type usersControllerFindAllResponseSuccess = (usersControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type usersControllerFindAllResponse = (usersControllerFindAllResponseSuccess)

export const getUsersControllerFindAllUrl = () => {




  return `/users`
}

/**
 * Retrieve a list of all users
 * @summary Get all users
 */
export const usersControllerFindAll = async ( options?: RequestInit): Promise<usersControllerFindAllResponse> => {

  return apiFetch<usersControllerFindAllResponse>(getUsersControllerFindAllUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerFindAllMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerFindAll>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerFindAll>>, TError,void, TContext> => {

const mutationKey = ['usersControllerFindAll'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerFindAll>>, void> = () => {


          return  usersControllerFindAll(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerFindAllMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerFindAll>>>

    export type UsersControllerFindAllMutationError = unknown

    /**
 * @summary Get all users
 */
export const useUsersControllerFindAll = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerFindAll>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerFindAll>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUsersControllerFindAllMutationOptions(options));
    }
    export type usersControllerFindOneResponse200 = {
  data: UserResponseDto
  status: 200
}

export type usersControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type usersControllerFindOneResponseSuccess = (usersControllerFindOneResponse200) & {
  headers: Headers;
};
export type usersControllerFindOneResponseError = (usersControllerFindOneResponse404) & {
  headers: Headers;
};

export type usersControllerFindOneResponse = (usersControllerFindOneResponseSuccess | usersControllerFindOneResponseError)

export const getUsersControllerFindOneUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * Retrieve a single user by their ID
 * @summary Get user by ID
 */
export const usersControllerFindOne = async (id: string, options?: RequestInit): Promise<usersControllerFindOneResponse> => {

  return apiFetch<usersControllerFindOneResponse>(getUsersControllerFindOneUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsersControllerFindOneMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerFindOne>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof usersControllerFindOne>>, TError,{id: string}, TContext> => {

const mutationKey = ['usersControllerFindOne'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersControllerFindOne>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  usersControllerFindOne(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UsersControllerFindOneMutationResult = NonNullable<Awaited<ReturnType<typeof usersControllerFindOne>>>

    export type UsersControllerFindOneMutationError = void

    /**
 * @summary Get user by ID
 */
export const useUsersControllerFindOne = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersControllerFindOne>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof usersControllerFindOne>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getUsersControllerFindOneMutationOptions(options));
    }
