/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * TeleV4 API
 * Telehealth Marketplace Platform — Backend REST API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HealthResponseDto
} from '../model';

import { apiFetch } from '../../utils/api';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type healthControllerCheckResponse200 = {
  data: HealthResponseDto
  status: 200
}

export type healthControllerCheckResponseSuccess = (healthControllerCheckResponse200) & {
  headers: Headers;
};
;

export type healthControllerCheckResponse = (healthControllerCheckResponseSuccess)

export const getHealthControllerCheckUrl = () => {




  return `/health`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthControllerCheck = async ( options?: RequestInit): Promise<healthControllerCheckResponse> => {

  return apiFetch<healthControllerCheckResponse>(getHealthControllerCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthControllerCheckMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError,void, TContext> => {

const mutationKey = ['healthControllerCheck'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof healthControllerCheck>>, void> = () => {


          return  healthControllerCheck(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HealthControllerCheckMutationResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheck>>>

    export type HealthControllerCheckMutationError = unknown

    /**
 * @summary Health check
 */
export const useHealthControllerCheck = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof healthControllerCheck>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getHealthControllerCheckMutationOptions(options));
    }
